### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by zckrs**
- `yeoman-generator` to v.0.20.1
- `mocha` define version instead wildcard

### CODE REVIEW

**Comment by sindresorhus** [comment]
The only dependency that actually needs updating is the `generator` one and I'd rather just do that when doing other improvements.

**Comment by zckrs** [comment]
Understood :disappointed:

**Comment by sindresorhus** [comment]
The reason is that I have to manually test it after doing a generator bump, which is some work, and I rather do that when I have to do it anyways because of other changes.

**Comment by zckrs** [comment]
I totally agree with you.

Note: I tested the generator after update the dependencies. No regressions are present. As you know EJS have a similiar syntax to Lodash templating.
The only important point is to use `<%=` or `<%-` to escape characters.

**Comment by sindresorhus** [comment]
Ok, cool. Then feel free to just update the generator dependency directly. But the other ones used `^` so no update needed. And I prefer to keep mocha at `*` as the version doesn't really matter there.

**Pull request closed without merging**
