### PR TITLE
Use new `fs` methods for file copying

### LINKED ISSUE #7: Use the new `fs` method for doing the file copying
http://yeoman.io/blog/release-0.18.html

Help welcome :)

### PR DESCRIPTION
**Pull request by kevva**
Fixes #7.

### CODE REVIEW

**Comment by zckrs** [comment]
:+1:

**Comment by arthurvr** [comment]
lgtm

**Comment by zckrs** [comment]
Tested locally. Everything works.

**Comment by sindresorhus** [comment]
_Gonna wait on doing a release until https://github.com/sindresorhus/generator-gulp-plugin-boilerplate/commit/d7503c081f025e6ce2f8665638d353e444ffc6e6#commitcomment-11796951 is done here too._

**Pull request merged**
